contact_links:
  - name: ğŸ“˜ Documentation
    url: https://github.com/thuliteio/docs
    about: File an issue or make an improvement to the docs website.
  - name: ğŸ’ Support
    url: https://github.com/orgs/thuliteio/discussions
    about: 'Get help on  Discussions'
