contact_links:
  - name: ğŸ“˜ Documentation
    url: https://github.com/gethyas/docs
    about: File an issue or make an improvement to the docs website.
  - name: ğŸ’ Support
    url: https://github.com/gethyas/hyas/discussions
    about: 'Get help on Hyas Discussions'
